### ISSUE TITLE
Uninstall Leaves Menu Item Behind

### ISSUE THREAD

**Issue by benhysell** [asudbury/NinjaCoderForMvvmCross#122]
Uninstalling from the Control Panel will uninstall NinjaCoder, however the menu item is still left behind in vs2013.

![screen shot 2014-03-21 at 8 20 58 am](https://f.cloud.github.com/assets/1711776/2482760/601c0dec-b0f3-11e3-9dfc-43b40ed1c17d.png)

**Comment by tbalcom** [comment]
How can I remove the menu?  I uninstalled this extension via Windows 7 Control Panel and the menu remains in Visual Studio 2013.

**Comment by asudbury** [comment]
Im hoping this will be fixed (though not for VS2013) with the version for VS2015 and the new VSIX installer.

**Comment by asudbury** [comment]
this shouldn't happen with the new VS2015 version 4.0.0 as we have now moved to a vsix installer.
