### ISSUE TITLE
Custom project names

### ISSUE THREAD

**Issue by tsahi** [asudbury/NinjaCoderForMvvmCross#128]
It would be nice if I could, during project creation or in the settings, to change the names of the projects ninja creates. e.g. I don't like the name .Droid, and would rather my Android project be named .Android

**Comment by asudbury** [comment]
@tsahi @CliffCawley at long last I now have a version in beta that supports this request - let me know if you can help test.

**Comment by CliffCawley** [comment]
@asudbury Ah sorry, I no longer use Mvvmcross (I've switched to Xamarin Forms)

**Comment by asudbury** [comment]
@CliffCawley it does now support Xamarin Forms :-)

**Comment by asudbury** [comment]
Released in version 4.1.0
