### ISSUE TITLE
VS freezes

### ISSUE THREAD

**Issue by powerdude** [asudbury/NinjaCoderForMvvmCross#135]
Hello,

I just installed NinjaCoder and was trying to create a project.  I selected everything but iOS and VS just locks up after creating Core, Core.Tests and Droid.

cliff

**Comment by asudbury** [comment]
Cliff can you tell me if this is still an issue with the latest release.

**Comment by tbalcom** [comment]
I'm using version 3.5.0 and it freezes Visual Studio 2013 for me 100% of the time when I try to use "Add ViewModel and Views".  I had a previous version before version 3.5.0, and it worked fine.  After I restart Visual Studio after the freeze I see some files were not completed.  "FirstViewModel" is referenced by the generated unit test.  I did not select the name "FirstViewModel".

Here is the log:

12 Jun 15 12:16:50 696  BaseController::Constructor
12 Jun 15 12:16:50 699  ViewModelAndViewsController::Constructor
12 Jun 15 12:16:50 701  **Setting DTE2**
12 Jun 15 12:16:50 704  --------------------------------------------------------
12 Jun 15 12:16:50 706  ViewModelAndViewsController::Run
12 Jun 15 12:16:50 708  --------------------------------------------------------
12 Jun 15 12:16:50 715  ProjectExtensions::GetProjectReferences project=Dispatch.Core
12 Jun 15 12:16:50 729  FrameworkFactory::Constructor
12 Jun 15 12:16:50 833  BaseController::GetLanguageDictionary
12 Jun 15 12:16:50 837  WizardFrameViewModel::Constructor Start
12 Jun 15 12:16:50 845  ProjectExtensions::GetFolderItems project=Dispatch.Core Folder=ViewModels
12 Jun 15 12:16:50 848  ProjectExtensions::GetFolder project=Dispatch.Core folderName=ViewModels
12 Jun 15 12:16:50 874  ProjectItemExtensions::GetSubProjectItems file=ViewModels
12 Jun 15 12:16:50 878  WizardFrameViewModel::Constructor End
12 Jun 15 12:17:14 855  ViewModelAndViewsController::Process
12 Jun 15 12:17:14 865  DTEExtensions::GetCSharpProjectItemsEvents
12 Jun 15 12:17:14 906  ViewModelAndViewsFactory::GetRequiredViewModelAndViews
12 Jun 15 12:17:14 910  ViewModelViewsService::AddViewModelAndViews
12 Jun 15 12:17:14 914  SolutionExtensions::AddItemTemplateToProjects
12 Jun 15 12:17:14 916  AddItemTemplateToProjectsDispatch.Core  (template=MvvmCross.ViewModel.Blank.zip) fileName=DataSyncViewModel.cs
12 Jun 15 12:17:14 919  ProjectExtensions::AddToFolderFromTemplate project=Dispatch.Core templateName=MvvmCross.ViewModel.Blank.zip fileName=DataSyncViewModel.cs
12 Jun 15 12:17:14 921  SolutionExtensions::GetProjectItemTemplate templateName=MvvmCross.ViewModel.Blank.zip
12 Jun 15 12:17:15 516  TemplatePath=C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\ItemTemplatesCache\CSharp\Ninja Coder\MvvmCross\ViewModels\MvvmCross.ViewModel.Blank.zip\MvvmCross.ViewModel.Blank.vstemplate
12 Jun 15 12:17:15 850  BaseController::ProjectItemsEventsItemAdded file=DataSyncViewModel.cs
12 Jun 15 12:17:15 853  BaseController::ProjectItemAdded
12 Jun 15 12:17:16 003  AddItemTemplateToProjectsDispatch.Droid  (template=MvvmCross.Droid.View.Blank.zip) fileName=DataSyncView.cs
12 Jun 15 12:17:16 005  ProjectExtensions::AddToFolderFromTemplate project=Dispatch.Droid templateName=MvvmCross.Droid.View.Blank.zip fileName=DataSyncView.cs
12 Jun 15 12:17:16 008  SolutionExtensions::GetProjectItemTemplate templateName=MvvmCross.Droid.View.Blank.zip
12 Jun 15 12:17:16 013  TemplatePath=C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\ItemTemplatesCache\CSharp\Ninja Coder\MvvmCross\Views\MvvmCross.Droid.View.Blank.zip\MvvmCross.Droid.View.Blank.vstemplate
12 Jun 15 12:17:16 086  BaseController::ProjectItemsEventsItemAdded file=DataSyncView.axml
12 Jun 15 12:17:16 092  BaseController::ProjectItemAdded
12 Jun 15 12:17:16 262  BaseController::ProjectItemsEventsItemAdded file=DataSyncView.cs
12 Jun 15 12:17:16 264  BaseController::ProjectItemAdded
12 Jun 15 12:17:18 838  AddItemTemplateToProjectsDispatch.Wpf  (template=MvvmCross.Wpf.View.Blank.zip) fileName=DataSyncView.cs
12 Jun 15 12:17:18 840  ProjectExtensions::AddToFolderFromTemplate project=Dispatch.Wpf templateName=MvvmCross.Wpf.View.Blank.zip fileName=DataSyncView.cs
12 Jun 15 12:17:18 842  SolutionExtensions::GetProjectItemTemplate templateName=MvvmCross.Wpf.View.Blank.zip
12 Jun 15 12:17:18 847  TemplatePath=C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\ItemTemplatesCache\CSharp\Ninja Coder\MvvmCross\Views\MvvmCross.Wpf.View.Blank.zip\MvvmCross.Wpf.View.Blank.vstemplate
12 Jun 15 12:17:19 965  BaseController::ProjectItemsEventsItemAdded file=DataSyncView.xaml
12 Jun 15 12:17:19 968  BaseController::ProjectItemAdded
12 Jun 15 12:17:20 027  BaseController::ProjectItemsEventsItemAdded file=DataSyncView.xaml.cs
12 Jun 15 12:17:20 031  BaseController::ProjectItemAdded
12 Jun 15 12:17:22 289  AddItemTemplateToProjectsDispatch.Core.Tests  (template=MvvmCross.NUnit.TestViewModel.Blank.zip) fileName=TestDataSyncViewModel.cs
12 Jun 15 12:17:22 292  ProjectExtensions::AddToFolderFromTemplate project=Dispatch.Core.Tests templateName=MvvmCross.NUnit.TestViewModel.Blank.zip fileName=TestDataSyncViewModel.cs
12 Jun 15 12:17:22 294  SolutionExtensions::GetProjectItemTemplate templateName=MvvmCross.NUnit.TestViewModel.Blank.zip
12 Jun 15 12:17:22 299  TemplatePath=C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\ItemTemplatesCache\CSharp\Ninja Coder\MvvmCross\TestViewModels\MvvmCross.NUnit.TestViewModel.Blank.zip\MvvmCross.NUnit.TestViewModel.Blank.vstemplate
12 Jun 15 12:17:22 587  BaseController::ProjectItemsEventsItemAdded file=TestDataSyncViewModel.cs
12 Jun 15 12:17:22 590  BaseController::ProjectItemAdded
12 Jun 15 12:17:22 739  ViewModelViewsService::UpdateUnitTestFile ViewModelName=DataSyncViewModel
12 Jun 15 12:17:22 743  ProjectExtensions::GetProjectItem project=Dispatch.Core.Tests fileName=TestDataSyncViewModel
12 Jun 15 12:17:22 745  ProjectExtensions::GetCSharpProjectItems project=Dispatch.Core.Tests
12 Jun 15 12:17:22 748  ProjectItemExtensions::GetSubProjectItems file=app.config
12 Jun 15 12:17:22 751  ProjectItemExtensions::GetSubProjectItems file=BaseTest.cs
12 Jun 15 12:17:22 753  ProjectItemExtensions::GetSubProjectItems file=Mocks
12 Jun 15 12:17:22 755  ProjectItemExtensions::GetSubProjectItems file=packages.config
12 Jun 15 12:17:22 757  ProjectItemExtensions::GetSubProjectItems file=Properties
12 Jun 15 12:17:22 760  ProjectItemExtensions::GetSubProjectItems file=TestTrace.cs
12 Jun 15 12:17:22 762  ProjectItemExtensions::GetSubProjectItems file=ViewModels
12 Jun 15 12:17:22 764  NUnitTestingService::UpdateTestClassAttribute
12 Jun 15 12:17:22 767  NUnitTestingService::UpdateTestMethodAttribute
12 Jun 15 12:17:22 769  BaseTestingService::UpdateFile
12 Jun 15 12:17:22 772  ProjectItemExtensions::ReplaceText in file TestDataSyncViewModel.cs from 'FirstViewModel' to 'DataSyncViewModel'

**Comment by asudbury** [comment]
can you try it without adding the iOS and Android projects to a test solution.

Sometimes Xamarin is the cause of issues - i just want to rule it in or out.

The actual command it is getting 'stuck' on is just replacing text - this hasnt changes since the very early days.

thanks

adrian.
