### ISSUE TITLE
MvvmCross and Xamarin Forms in the same solution

### ISSUE THREAD

**Issue by asudbury** [asudbury/NinjaCoderForMvvmCross#157]
Allow MvvmCross and Xamarin Forms to work in the same solution.

**Comment by asudbury** [comment]
All the code is written - have tested on Android and appears to work - my iOS setup and WindowsPhone emulator don't seem to want to work at the moment so asking for help :-(

**Comment by kreuzhofer** [comment]
If you like, I would support you in testing on iOS and WindowsPhone as I have some problems on WP with 3.3.0 as posted on the visualstudiogallery page.

**Comment by asudbury** [comment]
Contact me via Twitter and we can sort things #asudbury

**Comment by asudbury** [comment]
This installer below is version 3.3.1 which will be 3.4.0 we it goes public

https://dl.dropboxusercontent.com/u/3181019/NinjaCoderForMvxXamarinFormsInstaller.msi

Contains MvvmCross and Xamarin Forms integration - i believe it all works its just i can test you can view a Xamarin Forms page from a MvvmCross View model for WinPhone and IOS

Let me know if you want more info.

**Comment by asudbury** [comment]
Plan to push this public in the next few days and put on my tin hat :-)

I have other activities that need my time and from the lack of responses i'm not convinced too many people want this feature - which i'm a bit surprised by - quite a lot of effort when into this feature - you live and learn i guess!

**Comment by Michael-DST** [comment]
First off... thank you for being so active/progressive and embracing these technologies. :)

I just tried adding NinjaCoder Xamarin.Forms project and it just created an empty project.  Expected?

**Comment by Michael-DST** [comment]
Also, when I Tools -> Add Projects, MvvmCross and Xamarin.Forms is greyed/locked out.  That is, I cannot select it.  MvvmCross is selected.

https://www.dropbox.com/s/cdxce0ev35ox6al/Screenshot%202015-02-13%2005.51.29.png?dl=0

**Comment by asudbury** [comment]
Released in version 3.4.0
