### ISSUE TITLE
xUnit Support Please!

### ISSUE THREAD

**Issue by Michael-DST** [asudbury/NinjaCoderForMvvmCross#159]
Cannot believe this is not in there. :)  Please provide xUnit support, along with AutoFixture if possible.

**Comment by slodge** [comment]
Can't believe you haven't contributed it yet!

![image](https://cloud.githubusercontent.com/assets/533662/6186521/45fd4534-b372-11e4-8eac-0383316d614a.png)

**Comment by Michael-DST** [comment]
LOL!!!  Of course, what am I thinking!!! #durp

**Comment by asudbury** [comment]
Why cant you believe its not in there?

**Comment by Michael-DST** [comment]
It was a facetious statement. And I officially regret saying it now. :P

**Comment by asudbury** [comment]
if you can help with some info regarding xunit support I will take a look at adding it (xunit is a bit new to me!)

**Comment by Michael-DST** [comment]
Yes I would actually like to get this working w/ your extension.  I am currently working on a Xamarin.Forms project that is going to take a week or so.  Next step is to investigate MvvmCross+XF with your extension. :)  Once I have that figured out I will be in a great spot to help out, as I will be needing to build unit tests around what I write. :P 

If you want something to check out in the meantime, here is a great page: http://xunit.github.io/docs/running-tests-in-vs.html

It used to involve an extension but now it's all NuGet (yay).  Essentially it is just a matter of installing a NuGet project and you are set.  Pretty easy. :)  I am also a MASSIVE fan of @ploeh and his amazing AutoFixture project.  It's the reason why I am so sold on xUnit, or unit testing at all these days. :P 

I would recommend bolting it on as well, but I will leave it to your discretion whether or not it makes sense. :)

https://github.com/AutoFixture/AutoFixture

(AutoFixture does work w/ NUnit as well, but I have only used it w/ xUnit so hence a very strong association between the two!)

**Comment by asudbury** [comment]
Interesting.

I will start working on it today.

**Comment by asudbury** [comment]
this work has now been completed (I think) - will go out in next public release.

**Comment by Michael-DST** [comment]
Awesome!!!  Thank you for your efforts :D

**Comment by asudbury** [comment]
Released in version 3.4.0
