### ISSUE TITLE
NinajCoder.NUnit1

### ISSUE THREAD

**Issue by Michael-DST** [asudbury/NinjaCoderForMvvmCross#160]
Nuff said. :P

**Comment by slodge** [comment]
Hi @Michael-DST 

I'm not a contributor to or maintainer of this repo, but I do use the output and I am interested in using new stuff within it in the future.

Please excuse my ignorance, but I'm not really sure what `NinajCoder.NUnit1` means. I searched for "NUnit1", but sadly neither Google nor Bing could help... I guess you're busy and that this is really obvious stuff, but if you have time could you perhaps add some more content here? Maybe explaining what it is, maybe add links, maybe explaining why users should care and what should be added to NinjaCoder to make it even more awesome?

Always excited and interested in learning about new and better stuff.

Thanks

Stuart

**Comment by Michael-DST** [comment]
:)

https://www.dropbox.com/s/lyn1ohu6v1pr7ih/Screenshot%202015-02-13%2006.31.51.png?dl=0

:)

**Comment by Michael-DST** [comment]
Guess I should be contributing to this one, too, huh! :)

**Comment by Michael-DST** [comment]
Well, I found one, but it is not what is causing this issue.  T

After a (wholebuncha) hunting, I found the build settings that points to a template build file:
https://github.com/asudbury/Ninja4MvxInstaller/blob/master/Global.wxi

There's a directory that is used for the project templates:
B:\Scorchio\Projects\c#\Ninja\NinjaCodeMvvmCrossTemplates

And my guess is that is where the .zip file that contains the .vstemplate with the typo.  I could not find it anywhere in any of @asudbury's repo's.  So much for brownie points. :P

**Comment by asudbury** [comment]
Hi @Michael-DST 

I'm not sure what you are saying the problem is here.

To start the ninja you need to go to Tools | Ninja Coder for MvvmCross

**Comment by Michael-DST** [comment]
Thank you @asudbury for the reply... is that to start the ninja or the ninaj? :)  To be sure here, the issue is a typo. :)

Do you see it in this screenshot?
https://www.dropbox.com/s/lyn1ohu6v1pr7ih/Screenshot%202015-02-13%2006.31.51.png?dl=0

**Comment by asudbury** [comment]
to be honest typos are the laest of my worries!

**Comment by asudbury** [comment]
and the typo was deliberate :-)

**Comment by Michael-DST** [comment]
LOL!  Well I tried to fix it, but couldn't find it.  But my PR does find the other one I found. :)

**Comment by asudbury** [comment]
typo fixed will be available in the next release (if I can get someone to test it!)

**Comment by Michael-DST** [comment]
Hey I found it, I own it. :)  Sure, just let me know whenever you have the new .msi and I will check it out for you.

**Comment by asudbury** [comment]
the new msi contains the Xamarin forms and mvvmcross integration  - its a work in progress and I think you will find too many issues for me to cope with :-(

**Comment by Michael-DST** [comment]
Right I believe I checked it out this morning and added to an open issue around this.  It's a process!

**Comment by asudbury** [comment]
version 3.3.2 with your requested changes

https://dl.dropboxusercontent.com/u/3181019/NinjaCoderForMvxXamarinFormsInstaller.msi

**Comment by Michael-DST** [comment]
SUCCESS!!!

https://www.dropbox.com/s/vwv9kpb25merwsv/Screenshot%202015-02-13%2015.58.31.png?dl=0
