### ISSUE TITLE
Support for Xamarin.Forms for Windows

### ISSUE THREAD

**Issue by asudbury** [asudbury/NinjaCoderForMvvmCross#165]
Currently im preview only at the moment

**Comment by MobiliTips** [comment]
I'm currently working on NuSpec files for WinPhone & WinStore 8.1.
As XF packages are still on preview at the moment, if user check WinStore or/and WinPhone 8.1 project checkboxes on Ninja, it should automaticaly check "Use Nuget pre-release..." and probably "Use Ninja pre-release...".

For this purpose, I was wondering if it would be more consistent to reorder Ninja screens like that:

1. Framework selection > 2. Projects selection > 3. Test and prarameters (actual first screen) > 4. Plugins and so on...

Like so, depending if user checked MvvmCross & Xamarin Forms on screen 1 and WinStore or/and WinPhone 8.1 on screen 2, "Use pre-release..." checkboxes will be pre-checked and grayed (disabled) on screen 3.

What do you think?

**Comment by asudbury** [comment]
@MobiliTips I have a version of the Ninja that now supports WindowsStore 8.1 if you are interested in taking a look.

**Comment by MobiliTips** [comment]
I’ll try to take a look at it maybe this weekend.

Busy times :)

 

De : asudbury [mailto:notifications@github.com] 
Envoyé : dimanche 28 juin 2015 13:36
À : asudbury/NinjaCoderForMvvmCross
Cc : Jeremy BRUN-PICARD
Objet : Re: [NinjaCoderForMvvmCross] Support for Xamarin.Forms for Windows (#165)

 

@MobiliTips <https://github.com/MobiliTips>  I have a version of the Ninja that now supports WindowsStore 8.1 if you are interested in taking a look.

**Comment by asudbury** [comment]
released as part of v.3.6.0 (only windows store - windows 8.1 in a future release)
