### ISSUE TITLE
Add SplashScreen files to Android projects

### ISSUE THREAD

**Issue by MobiliTips** [asudbury/NinjaCoderForMvvmCross#167]
Files already added.
Just target the Scorchio.NinjaCoder.MvvmCross.1.0.1 nuget package to Xamarin.iOS10 and MonoAndroid as it contains droid splash screen files.
For now it only target Xamarin.iOS10

**Comment by asudbury** [comment]
is this the correct files (i havent actually changed anything)

      
      <file src="DroidContent\Resources\Drawable\splash.png" target="content\MonoAndroid\Resources\Drawable\splash.png" />
      <file src="DroidContent\Resources\Values\SplashStyle.xml" target="content\MonoAndroid\Resources\Values\SplashStyle.xml" />
			
		
	
		<file src="iOSContent\AppDelegate.cs.pp" target="content\Xamarin.iOS10\AppDelegate.cs.pp" />
		<file src="iOSContent\LinkerPleaseInclude.cs.pp" target="content\Xamarin.iOS10\LinkerPleaseInclude.cs.pp" />
		<file src="iOSContent\Main.cs.pp" target="content\Xamarin.iOS10\Main.cs.pp" />
		<file src="iOSContent\Setup.cs.pp" target="content\Xamarin.iOS10\Setup.cs.pp" />

    <file src="iOSContent\Views\BaseView.cs.pp" target="content\Xamarin.iOS10\Views\BaseView.cs.pp" />

**Comment by MobiliTips** [comment]
Yes it is


Envoyé depuis un mobile Samsung.

<div>-------- Message d'origine --------</div><div>De : asudbury <notifications@github.com> </div><div>Date :11/04/2015  12:41  (GMT+01:00) </div><div>A : asudbury/NinjaCoderForMvvmCross <NinjaCoderForMvvmCross@noreply.github.com> </div><div>Cc : Jeremy BRUN-PICARD <mobilitips@hotmail.com> </div><div>Objet : Re: [NinjaCoderForMvvmCross] Add SplashScreen files to Android projects (#167) </div><div>
</div>
is this the correct files (i havent actually changed anything)

      
      <file src="DroidContent\Resources\Drawable\splash.png" target="content\MonoAndroid\Resources\Drawable\splash.png" />
      <file src="DroidContent\Resources\Values\SplashStyle.xml" target="content\MonoAndroid\Resources\Values\SplashStyle.xml" />

                

                <file src="iOSContent\AppDelegate.cs.pp" target="content\Xamarin.iOS10\AppDelegate.cs.pp" />
                <file src="iOSContent\LinkerPleaseInclude.cs.pp" target="content\Xamarin.iOS10\LinkerPleaseInclude.cs.pp" />
                <file src="iOSContent\Main.cs.pp" target="content\Xamarin.iOS10\Main.cs.pp" />
                <file src="iOSContent\Setup.cs.pp" target="content\Xamarin.iOS10\Setup.cs.pp" />

    <file src="iOSContent\Views\BaseView.cs.pp" target="content\Xamarin.iOS10\Views\BaseView.cs.pp" />

---

**Comment by asudbury** [comment]
new version (1.0.1.beta4) uploaded to nuget to include Droid content.

**Comment by asudbury** [comment]
did 1.0.1 beta 4 fix things?

**Comment by MobiliTips** [comment]
I'll give a try tomorrow if you don't beat me :) weather here in france was so nice this weekend so I just can't stay at home (and I have to deal with my wife :) )


Envoyé depuis un mobile Samsung.

<div>-------- Message d'origine --------</div><div>De : asudbury <notifications@github.com> </div><div>Date :12/04/2015  18:56  (GMT+01:00) </div><div>A : asudbury/NinjaCoderForMvvmCross <NinjaCoderForMvvmCross@noreply.github.com> </div><div>Cc : Jeremy BRUN-PICARD <mobilitips@hotmail.com> </div><div>Objet : Re: [NinjaCoderForMvvmCross] Add SplashScreen files to Android projects (#167) </div><div>
</div>
did 1.0.1 beta 4 fix things?

---

**Comment by asudbury** [comment]
ok thanks - weather here in England is rubbish - but then it always is :-(

**Comment by MobiliTips** [comment]
Just tested and... nothing changed :(
I mean the package Scorchio.NinjaCoder.MvvmCross.1.0.1 is not installed in the Droid project, only the iOS one. MonoDroid should be added to the package target framework

**Comment by asudbury** [comment]
Oh!!

Any errors in the nuget console window?

**Comment by MobiliTips** [comment]
Just checked the package from nuget.org with NPE and seems to be ok.
The nuget console doesn't talk about Scorchio.NinjaCoder.MvvmCross.1.0.1 installation on Droid project, only iOS.

**Comment by asudbury** [comment]
Sounds like it might need a code change :-(

**Comment by asudbury** [comment]
new installer (v3.4.3)  to reference Scorchio.NinjaCoder.MvvmCross for Android Projects.

https://dl.dropboxusercontent.com/u/3181019/NinjaCoderForMvxXamarinFormsInstaller.msi

**Comment by MobiliTips** [comment]
:)))))) here we are!!
iOS, Android and WinPhone SL finaly work great almost right after ninja creation!
I said "almost" because there's one last thing I still have to do before hiting F5.
Into the Forms project, the MainView's ContentView is still empty so I had to add something like:

    <Label Text="{Binding SampleText}" HorizontalOptions="Center" VerticalOptions="Center"><\label>

We should add this but don't really know where, I mean Nuget vs Template.
Anyway, I close this issue as it's solved and open a new one for this last thing.

**Comment by asudbury** [comment]
i have this

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage x:Class="Fffffffff.Forms.Views.MainView"
             xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:viewModels="clr-namespace:Fffffffff.Core.ViewModels;assembly=Fffffffff.Core"
             Title="MainView Page">
    <ContentPage.BindingContext>
        <viewModels:MainViewModel />
    </ContentPage.BindingContext>
    <ContentView>
        <Label HorizontalOptions="Center"
               Text="{Binding SampleText}"
               VerticalOptions="Center" />
    </ContentView>
</ContentPage>
