### ISSUE TITLE
Add SampleText binding into MainView's ContentView

### ISSUE THREAD

**Issue by MobiliTips** [asudbury/NinjaCoderForMvvmCross#168]
Into the Forms project, the MainView's ContentView is still empty so I had to add something like:

    <Label Text="{Binding SampleText}" HorizontalOptions="Center" VerticalOptions="Center"><\label>

We should add this but don't really know where, I mean Nuget vs Template.

**Comment by asudbury** [comment]
I'll take a look later. We are  nearly finished :-)

**Comment by MobiliTips** [comment]
I get it.
The problem is when user doesn't check "Bind Context in xaml" checkbox, there isn't any Label anymore in MainView.xaml.
Unchecking this checkbox should only remove the Context binding from xaml, not the Label.

Anyway, we should never bind Context into xaml if user selected MvvmCross & Xamarin.Forms. Doing so throw an exception when user try to inject a service from the ViewModel constructor (XF can't find a constructor without any parameter). This is why our presenters bind the context to the views as the presenter can construct the ViewModel, resovling any services if needed.

**Comment by asudbury** [comment]
So if I take the binding out of the xaml for BOTH Xamarin Forms only option and Xamarin Forms and MvvmCross option things should then work for both options?

**Comment by MobiliTips** [comment]
No it won't :( sorry.
In both case we need to bind context to view so that our SampleText could appear on screen.

* With Xamarin.Forms and MvvmCross option, we let the mvx presenter manage context binding to deal with potential dependency injection into ViewModel constructor.
* With Xamarin.Forms only option, we need to bind context somewhere (into the xaml as you did or into the xaml.cs)

If you remove xaml context binding from both, user will have to add it manually if he selected Xamarin.Forms only option.

**Comment by asudbury** [comment]
So if I take out the binding in the xaml just for Xamarin forms AND MvvmCross it will work for both options.

**Comment by MobiliTips** [comment]
Yes it will :)

 

De : asudbury [mailto:notifications@github.com] 
Envoyé : mercredi 15 avril 2015 11:49
À : asudbury/NinjaCoderForMvvmCross
Cc : Jeremy BRUN-PICARD
Objet : Re: [NinjaCoderForMvvmCross] Add SampleText binding into MainView's ContentView (#168)

 

So if I take out the binding in the xaml just for Xamarin forms AND MvvmCross it will work for both options.

**Comment by asudbury** [comment]
I must admit im not sure what is the best way to solve this.

Ideally i would like the binding in xaml to work for both options but can see the constructor injection is going to fail.

I think the first thing i need to remove "Bind Context in xaml" option first and we will decide how it will be done.

**Comment by MobiliTips** [comment]
Sounds good to me. Will take a look later on injection with xaml context binding (some ideas already).
After xaml binding removal, we should be good to push all in stable version (pkg + msi), well, after a final try to be sure :)
Then, if you're ok with that, I'll create a dev github branch and we'll start from here with windows store integration.

Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : asudbury <notifications@github.com>
Date : 15/04/2015  19:48  (GMT+01:00)
À : asudbury/NinjaCoderForMvvmCross <NinjaCoderForMvvmCross@noreply.github.com>
Cc : Jeremy BRUN-PICARD <mobilitips@hotmail.com>
Objet : Re: [NinjaCoderForMvvmCross] Add SampleText binding into MainView's ContentView (#168)

I must admit im not sure what is the best way to solve this.

Ideally i would like the binding in xaml to work for both options but can see the constructor injection is going to fail.

I think the first thing i need to remove "Bind Context in xaml" option first and we will decide how it will be done.



---

**Comment by asudbury** [comment]
new installer :-1: 

https://dl.dropboxusercontent.com/u/3181019/NinjaCoderForMvxXamarinFormsInstaller.msi

**Comment by asudbury** [comment]
another new installer - should fix the xaml binding issues.

https://dl.dropboxusercontent.com/u/3181019/NinjaCoderForMvxXamarinFormsInstaller.msi

not sure if all the nuget packages are correct - but lets see if it works for you first @MobiliTips

**Comment by MobiliTips** [comment]
xaml binding issue fixed :)

but now you're right, some confusion with nuget packages.
It's all about Core project where CrossCore assembly is missing.
When you take a look at packages.config, there's only Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms.Core installed.

**Comment by asudbury** [comment]
taking a look now.

in my test project i have

<packages>
  <package id="MvvmCross.HotTuna.CrossCore" version="3.5.0" targetFramework="portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10" />
  <package id="MvvmCross.HotTuna.MvvmCrossLibraries" version="3.5.0" targetFramework="portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10" />
  <package id="MvvmCross.PortableSupport" version="3.5.0" targetFramework="portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10" />
  <package id="Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms.Core" version="1.0.2-beta2" targetFramework="portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10" />
</packages>

**Comment by asudbury** [comment]
MvvmCross.HotTuna.CrossCore" version="3.5.0" targetFramework="portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10" 
  MvvmCross.HotTuna.MvvmCrossLibraries" version="3.5.0" targetFramework="portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10"
  MvvmCross.PortableSupport" version="3.5.0" targetFramework="portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10"
  Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms.Core" version="1.0.2-beta2" targetFramework="portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10"

**Comment by asudbury** [comment]
and here are my nuget commands that were execute

Install-Package MvvmCross.HotTuna.MvvmCrossLibraries -FileConflictAction Overwrite -ProjectName Jjjjjjjj.Core 
Install-Package Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms.Core –IncludePrerelease  -FileConflictAction Overwrite -ProjectName Jjjjjjjj.Core 
Install-Package Scorchio.NinjaCoder.MvvmCross.NUnit.Tests –IncludePrerelease  -FileConflictAction ignore -ProjectName Jjjjjjjj.Core.Tests 
Install-Package Moq -FileConflictAction ignore -ProjectName Jjjjjjjj.Core.Tests 
Install-Package Scorchio.NinjaCoder.NUnit.Tests –IncludePrerelease  -FileConflictAction ignore -ProjectName Jjjjjjjj.Core.Tests 
Install-Package Xamarin.Forms -FileConflictAction Overwrite -ProjectName Jjjjjjjj.Forms 
Install-Package Scorchio.NinjaCoder.Xamarin.Forms –IncludePrerelease  -FileConflictAction Overwrite -ProjectName Jjjjjjjj.Forms 
Install-Package Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms –IncludePrerelease  -FileConflictAction Overwrite -ProjectName Jjjjjjjj.Forms 
Install-Package MvvmCross.HotTuna.MvvmCrossLibraries -FileConflictAction Overwrite -ProjectName Jjjjjjjj.iOS 
Install-Package Scorchio.NinjaCoder.MvvmCross –IncludePrerelease  -FileConflictAction ignore -ProjectName Jjjjjjjj.iOS 
Install-Package Xamarin.Forms -FileConflictAction Overwrite -ProjectName Jjjjjjjj.iOS 
Install-Package Scorchio.NinjaCoder.Xamarin.Forms –IncludePrerelease  -FileConflictAction Overwrite -ProjectName Jjjjjjjj.iOS 
Install-Package Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms –IncludePrerelease  -FileConflictAction Overwrite -ProjectName Jjjjjjjj.iOS 
Install-Package MvvmCross.HotTuna.MvvmCrossLibraries -FileConflictAction Overwrite -ProjectName Jjjjjjjj.Droid 
Install-Package Scorchio.NinjaCoder.MvvmCross –IncludePrerelease  -FileConflictAction ignore -ProjectName Jjjjjjjj.Droid 
Install-Package Xamarin.Android.Support.v4 -FileConflictAction ignore -ProjectName Jjjjjjjj.Droid 
Install-Package Xamarin.Forms -FileConflictAction Overwrite -ProjectName Jjjjjjjj.Droid 
Install-Package Scorchio.NinjaCoder.Xamarin.Forms –IncludePrerelease  -FileConflictAction Overwrite -ProjectName Jjjjjjjj.Droid 
Install-Package Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms –IncludePrerelease  -FileConflictAction Overwrite -ProjectName Jjjjjjjj.Droid 
Install-Package MvvmCross.HotTuna.MvvmCrossLibraries -FileConflictAction Overwrite -ProjectName Jjjjjjjj.WindowsPhone 
Install-Package Xamarin.Forms -FileConflictAction Overwrite -ProjectName Jjjjjjjj.WindowsPhone 
Install-Package Scorchio.NinjaCoder.Xamarin.Forms –IncludePrerelease  -FileConflictAction Overwrite -ProjectName Jjjjjjjj.WindowsPhone 
Install-Package Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms –IncludePrerelease  -FileConflictAction Overwrite -ProjectName Jjjjjjjj.WindowsPhone

**Comment by asudbury** [comment]
i dont get the error you are getting - ive rebuilt the installer (version 3.4.7) - if you want to give it a go.

https://dl.dropboxusercontent.com/u/3181019/NinjaCoderForMvxXamarinFormsInstaller.msi

does the package manager console give any errors?

also checked in the code to github!

**Comment by MobiliTips** [comment]
Ok now:
* Core is ok
* Forms is ok
* Droid is ok
* iOS is ok
* Windows Phone is not ok anymore :(

It seems that App.xaml.cs left some classic MvvmCross code lines for Setup initialization:

    Setup setup = new Setup(RootFrame);
    setup.Initialize();

and

    RootFrame.Dispatcher.BeginInvoke(() => Cirrious.CrossCore.Mvx.Resolve<Cirrious.MvvmCross.ViewModels.IMvxAppStart>().Start());

Don't know what could explain this change? Maybe you know.
Anyway, when this fixed, we'll be done for real! (did I ever say that already? :) )

**Comment by asudbury** [comment]
lol - will take a look 

i must admit i've got bored with this and was on the verge of giving up :-(

i think i change the nuget packages around to fix one problem and caused another one.

thanks your help - i do think we are nearly there - i'm sure i said at least 3 times before - sorry!

**Comment by asudbury** [comment]
the problem is i tried to be clever with the nuget packages and create a sort of hierarchy but it looks like that has failed!

**Comment by asudbury** [comment]
@MobiliTips  - it seems to work for me - can you try again please. and post up your NnjaReadMe.txt if it doesnt work.

**Comment by MobiliTips** [comment]
@asudbury Same: no Setup class initialization on WinPhone App.xaml.cs
Any msi rebuild needed?

MvvmCross and Xamarin Forms framework selected.

NinjaTest.Core project successfully added. (template MvvmCross.Core.zip)
NinjaTest.Forms project successfully added. (template NinjaCoder.Xamarin.Forms.zip)
NinjaTest.iOS project successfully added. (template NinjaCoder.iOS.zip)
NinjaTest.Droid project successfully added. (template MvvmCross.Droid.zip)
NinjaTest.WindowsPhone project successfully added. (template MvvmCross.WindowsPhone.zip)
MainViewModel.cs added to NinjaTest.Core project (template=XamarinForms.ViewModel.Blank.zip)
MainView.cs added to NinjaTest.Forms project (template=Xamarin.Forms.View.Blank.zip)
TestMainViewModel.cs added to NinjaTest.Core project (template=MvvmCross.NUnit.TestViewModel.Blank.zip)
TestMainViewModel.cs added to NinjaTest.Forms project (template=MvvmCross.NUnit.TestViewModel.Blank.zip)
TestMainViewModel.cs added to NinjaTest.iOS project (template=MvvmCross.NUnit.TestViewModel.Blank.zip)
TestMainViewModel.cs added to NinjaTest.Droid project (template=MvvmCross.NUnit.TestViewModel.Blank.zip)
TestMainViewModel.cs added to NinjaTest.WindowsPhone project (template=MvvmCross.NUnit.TestViewModel.Blank.zip)


----------------------------------------------------------------------------------------------------
Nuget Commands
----------------------------------------------------------------------------------------------------

Install-Package MvvmCross.HotTuna.MvvmCrossLibraries -FileConflictAction Overwrite -ProjectName NinjaTest.Core 
Install-Package Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms.Core –IncludePrerelease  -FileConflictAction Overwrite -ProjectName NinjaTest.Core 
Install-Package Xamarin.Forms -FileConflictAction Overwrite -ProjectName NinjaTest.Forms 
Install-Package Scorchio.NinjaCoder.Xamarin.Forms –IncludePrerelease  -FileConflictAction Overwrite -ProjectName NinjaTest.Forms 
Install-Package Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms –IncludePrerelease  -FileConflictAction Overwrite -ProjectName NinjaTest.Forms 
Install-Package MvvmCross.HotTuna.MvvmCrossLibraries -FileConflictAction Overwrite -ProjectName NinjaTest.iOS 
Install-Package Scorchio.NinjaCoder.MvvmCross –IncludePrerelease  -FileConflictAction ignore -ProjectName NinjaTest.iOS 
Install-Package Xamarin.Forms -FileConflictAction Overwrite -ProjectName NinjaTest.iOS 
Install-Package Scorchio.NinjaCoder.Xamarin.Forms –IncludePrerelease  -FileConflictAction Overwrite -ProjectName NinjaTest.iOS 
Install-Package Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms –IncludePrerelease  -FileConflictAction Overwrite -ProjectName NinjaTest.iOS 
Install-Package MvvmCross.HotTuna.MvvmCrossLibraries -FileConflictAction Overwrite -ProjectName NinjaTest.Droid 
Install-Package Scorchio.NinjaCoder.MvvmCross –IncludePrerelease  -FileConflictAction ignore -ProjectName NinjaTest.Droid 
Install-Package Xamarin.Android.Support.v4 -FileConflictAction ignore -ProjectName NinjaTest.Droid 
Install-Package Xamarin.Forms -FileConflictAction Overwrite -ProjectName NinjaTest.Droid 
Install-Package Scorchio.NinjaCoder.Xamarin.Forms –IncludePrerelease  -FileConflictAction Overwrite -ProjectName NinjaTest.Droid 
Install-Package Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms –IncludePrerelease  -FileConflictAction Overwrite -ProjectName NinjaTest.Droid 
Install-Package MvvmCross.HotTuna.MvvmCrossLibraries -FileConflictAction Overwrite -ProjectName NinjaTest.WindowsPhone 
Install-Package Xamarin.Forms -FileConflictAction Overwrite -ProjectName NinjaTest.WindowsPhone 
Install-Package Scorchio.NinjaCoder.Xamarin.Forms –IncludePrerelease  -FileConflictAction Overwrite -ProjectName NinjaTest.WindowsPhone 
Install-Package Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms –IncludePrerelease  -FileConflictAction Overwrite -ProjectName NinjaTest.WindowsPhone

**Comment by asudbury** [comment]
if you run the following manually does it work?

Install-Package Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms –IncludePrerelease -FileConflictAction Overwrite -ProjectName NinjaTest.WindowsPhone

**Comment by MobiliTips** [comment]
NinjaTest.WindowsPhone already has a reference to 'Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms 1.0.8-beta9'.

 

But App.xaml.cs still missing setup init.

 

De : asudbury [mailto:notifications@github.com] 
Envoyé : lundi 20 avril 2015 20:51
À : asudbury/NinjaCoderForMvvmCross
Cc : Jeremy BRUN-PICARD
Objet : Re: [NinjaCoderForMvvmCross] Add SampleText binding into MainView's ContentView (#168)

 

if you run the following manually does it work?

Install-Package Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms –IncludePrerelease -FileConflictAction Overwrite -ProjectName NinjaTest.WindowsPhone

**Comment by asudbury** [comment]
try the update command

Update-Package –reinstall Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms –IncludePrerelease -FileConflictAction Overwrite -ProjectName NinjaTest.WindowsPhone

https://docs.nuget.org/consume/reinstalling-packages

**Comment by asudbury** [comment]
if you use the NPE application does the source code look correct for App.xaml.cs?

**Comment by MobiliTips** [comment]
Thanks to NPE, I can see there isn’t any App.xaml.cs.pp into the wp8 content folder of Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms

I don’t understand wich scorchio plugin should install mvvmcross base config files.

 

As far as I understood, Scorchio.NinjaCoder.MvvmCross should take care of all base MvvmCross config on each platform and then Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms should take care of XF modifications but Scorchio.NinjaCoder.MvvmCross doesn’t host any wp8 content folder (only Droid and iOS).

 

Well, I think I’m lost :)

 

 

De : asudbury [mailto:notifications@github.com] 
Envoyé : lundi 20 avril 2015 21:14
À : asudbury/NinjaCoderForMvvmCross
Cc : Jeremy BRUN-PICARD
Objet : Re: [NinjaCoderForMvvmCross] Add SampleText binding into MainView's ContentView (#168)

 

if you use the NPE application does the source code look correct for App.xaml.cs?

**Comment by asudbury** [comment]
thanks - good info - i will take a look.

**Comment by asudbury** [comment]
ok i think i know how to solve this :-)

but not tonight!

**Comment by MobiliTips** [comment]
Lol ok no problem

 

Getting back to the walking dead :)

 

De : asudbury [mailto:notifications@github.com] 
Envoyé : lundi 20 avril 2015 21:43
À : asudbury/NinjaCoderForMvvmCross
Cc : Jeremy BRUN-PICARD
Objet : Re: [NinjaCoderForMvvmCross] Add SampleText binding into MainView's ContentView (#168)

 

ok i think i know how to solve this :-)

but not tonight!

**Comment by asudbury** [comment]
Nuget package updated - hopefully we should now be good to go :-)

**Comment by MobiliTips** [comment]
Still the same pb but... I know why:

Attempting to resolve dependency 'MvvmCross.HotTuna.CrossCore (≥ 3.5.0)'.
Attempting to resolve dependency 'MvvmCross.PortableSupport (≥ 3.5.0)'.
'MvvmCross.HotTuna.MvvmCrossLibraries 3.5.0' already installed.
Adding 'MvvmCross.PortableSupport 3.5.0' to NinjaTest.WindowsPhone.
Successfully added 'MvvmCross.PortableSupport 3.5.0' to NinjaTest.WindowsPhone.
Adding 'MvvmCross.HotTuna.CrossCore 3.5.0' to NinjaTest.WindowsPhone.
Successfully added 'MvvmCross.HotTuna.CrossCore 3.5.0' to NinjaTest.WindowsPhone.
Adding 'MvvmCross.HotTuna.MvvmCrossLibraries 3.5.0' to NinjaTest.WindowsPhone.
Successfully added 'MvvmCross.HotTuna.MvvmCrossLibraries 3.5.0' to NinjaTest.WindowsPhone.

Attempting to resolve dependency 'WPtoolkit (≥ 4.2013.08.16)'.
Installing 'WPtoolkit 4.2013.08.16'.
Successfully installed 'WPtoolkit 4.2013.08.16'.
Adding 'WPtoolkit 4.2013.08.16' to NinjaTest.WindowsPhone.
Successfully added 'WPtoolkit 4.2013.08.16' to NinjaTest.WindowsPhone.
Adding 'Xamarin.Forms 1.4.2.6355' to NinjaTest.WindowsPhone.
Successfully added 'Xamarin.Forms 1.4.2.6355' to NinjaTest.WindowsPhone.

'Scorchio.NinjaCoder.Xamarin.Forms 1.0.12-beta7' already installed.
Adding 'Scorchio.NinjaCoder.Xamarin.Forms 1.0.12-beta7' to NinjaTest.WindowsPhone.
Overwrite existing file 'MainPage.xaml'.
Overwrite existing file 'MainPage.xaml.cs'.
Overwrite existing file 'App.xaml'.
Overwrite existing file 'App.xaml.cs'.
Successfully added 'Scorchio.NinjaCoder.Xamarin.Forms 1.0.12-beta7' to NinjaTest.WindowsPhone.

'Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms 1.0.8-beta9' already installed.
Adding 'Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms 1.0.8-beta9' to NinjaTest.WindowsPhone.
Overwrite existing file 'Setup.cs'.
Overwrite existing file 'MainPage.xaml'.
Overwrite existing file 'MainPage.xaml.cs'.
Successfully added 'Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms 1.0.8-beta9' to NinjaTest.WindowsPhone.

First we install MvvmCross wich put the right App.xaml.cs and then we install Scorchio.NinjaCoder.Xamarin.Forms wih overwrite App.xaml.cs with a non-MvvmCross one.
That's why!

One simple solution could be to add the good App.xaml.cs to Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms so that it finaly overwrite it back to the first good version.
What do you think?

**Comment by asudbury** [comment]
to be honest that's what i thought i did :-(

can you look at NPE and see what the source is saying - maybe i have the wrong source file (again!!!)

**Comment by asudbury** [comment]
have committed changes to github

**Comment by MobiliTips** [comment]
![ninja_mvxforms_wp](https://cloud.githubusercontent.com/assets/10962422/7260284/3e4e37fe-e869-11e4-9e3a-8d684f7788d5.png)

No App.xaml.cs.pp into wp8 content as you can see.

**Comment by asudbury** [comment]
thats the wrong version - i should have created beta-91 instead of beta10

Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms 1.0.8-beta91 added can you try again (and make sure you get this version)

**Comment by MobiliTips** [comment]
Lol...

'Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms 1.0.8-beta91' already installed.
Adding 'Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms 1.0.8-beta91' to NinjaTest.WindowsPhone.
Overwrite existing file 'Setup.cs'.
Overwrite existing file 'MainPage.xaml'.
Overwrite existing file 'MainPage.xaml.cs'.
Overwrite existing file 'App.xaml'.
Overwrite existing file 'App.xaml.cs'.
Successfully added 'Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms 1.0.8-beta91' to NinjaTest.WindowsPhone.

Overwrite ok but still the wrong App.xaml.cs :s

**Comment by asudbury** [comment]
ok ive checked into nuget - can you take a look please - im rubbish!

**Comment by MobiliTips** [comment]
Ok App.xaml.cs.pp updated and checked in. You should just have to update nuget pkg

**Comment by asudbury** [comment]
ok nuget updated with v92!

**Comment by MobiliTips** [comment]
Woooohoooo! Here we are!
* Core ok
* Forms ok
* iOS ok
* Droid ok
* WinPhone ok

Now you can push all to stable if you want and let people know.
Nice job!
And good night :)

**Comment by asudbury** [comment]
ok will sort it tomorrow - need to make sure i dont mess up!

thanks for all your help - much appreciated :-)

**Comment by asudbury** [comment]
@MobiliTips 

all nuget packages now public on github - them seem ok

new version of the ninja required though - installer below

https://dl.dropboxusercontent.com/u/3181019/NinjaCoderForMvxXamarinFormsInstaller.msi

i will push public once you say its ok.

**Comment by MobiliTips** [comment]
Just tested all again, and:

* All MvxForms projects work great! We did a good job on it! Yeah! :)
* All Mvx only projects work great! You did a good job on it! Oh yeah! :D
* All Forms only projects first screen are empty! Damn! :(

Ok I'll dig on Forms only projects this afternoon. 
We are progressing... definitly!

Keep dev faith! :p

**Comment by MobiliTips** [comment]
Ok I get it about Forms only projects empty screen:

In Forms project, in XamarinFormsApp class constructor, we have to set the MainPage property to new MainView();. In a Mvx context, it is MvvmCross wich define it thanks to this.RegisterAppStart<MainViewModel>(); but without Mvx, Xamarin Forms needs to know what is the MainPage.

With that modification, iOS and Android work great but something still left for WinPhone:

In the App.xaml.cs, we have to remove event subscrition from Application_Launching method as it is Xamarin.Forms wich manage navigation.
Also we could add CheckForResetNavigation method to be up to date with latest WinPhone implementation.

I update ninja nuspec and let you know when checked in.

**Comment by MobiliTips** [comment]
Checked in.
You'll have to update both Scorchio.NinjaCoder.Xamarin.Forms and Scorchio.NinjaCoder.MvvmCross.Xamarin.Forms with its own XamarinFormsApp.cs.pp in FormsContent and App.xaml.cs.pp in WindowsPhoneContent.
Let me know when done so I could try.

**Comment by asudbury** [comment]
have updated the 2 nuget packages - can you give it a go @MobiliTips

**Comment by MobiliTips** [comment]
Damn! I forgot to add "using Views;" into Forms only XamarinFormsApp class so that "MainPage = new MainView();" could work.

"using" just added and checked to GitHub so you'll have to update (again...) Scorchio.NinjaCoder.Xamarin.Forms with its latest XamarinFormsApp.cs.pp version.

Sorry about that :s

**Comment by MobiliTips** [comment]
It's official :D
All projects from all templates (Mvx only, Forms only and MvxForms) work great now and right after Ninja creation!
We made it!

Well, except that when you check WPF project for Mvx only, no WPF project created... but it's not really a big deal and it's not about what we were working on so long.
I'll close this issue and create a new one for WPF.
