### ISSUE TITLE
No WPF project created when option checked with MvvmCross only template

### ISSUE THREAD

**Issue by MobiliTips** [asudbury/NinjaCoderForMvvmCross#169]
No WPF project created when option checked with MvvmCross only template

**Comment by MobiliTips** [comment]
Log:

ERROR NinjaMvx.Wpf not added. exception Can't find specified file (from french translation :) ). (Exception from HRESULT: 0x80070002) (template NinjaCoder.Wpf.zip)

It seems it can't find the Wpf template

**Comment by asudbury** [comment]
fixed - it was a typo in the installer - will be pushing 3.5.0 public in the next hour - thanks for your help.

**Comment by asudbury** [comment]
fixed in v3.5.0
