### ISSUE TITLE
Unified support vor non-pre MvvmCross

### ISSUE THREAD

**Issue by lothrop** [asudbury/NinjaCoderForMvvmCross#175]
I created a new MvvmCross project and did not check the checkbox to use a prerelease version of MvvmCross. I noticed the iOS code still uses RectangleF although that was replaced by CGRect with the Unified API and MvvmCross 3.5. I don't think the old pre-Unified templates should still be in NinjaCoder.

**Comment by asudbury** [comment]
have managed to recreate - looked like the SampleData item template file SampleDataView.cs is incorrect.

references to RectangleF replaced with CGRect - will be in the next release (will try and fix a few more issues first before public release)

If you require a build just for this let me know i can provide a link to a private build here.

**Comment by asudbury** [comment]
released as part of v.3.6.0
