### ISSUE TITLE
Switch iOS template to XIB

### ISSUE THREAD

**Issue by lothrop** [asudbury/NinjaCoderForMvvmCross#191]
Now that there is a XIB designer in Xamarin Studio and Visual Studio I propose the sample code (using absolute positioning) be replaced with an example using XIBs and auto layouts. See https://github.com/lothrop/MvvmCrossDemo for an example.

**Comment by asudbury** [comment]
looks good - didn't  realise this was possible - will try incorporate in v4.0 or release soon after.

**Comment by asudbury** [comment]
Does this require Xamarin 4? 

I tried to include in my last build - but it complained - cant remember the error.

**Comment by lothrop** [comment]
It is nicer with Xamarin 4 since there is a built in XIB editor. It works with Xamarin 3, too. Clicking the XIB file then opens Interface Builder on the Mac.

**Comment by lothrop** [comment]
See https://github.com/MvvmCross/MvvmCross/pull/1196

**Comment by asudbury** [comment]
@lothrop i noticed there is also an option of using storyboards - is there an example anywhere?

i'm thinking of providing that as an option too!

**Comment by lothrop** [comment]
Yes, see http://kerry.lothrop.de/ios-ui-with-mvvmcross/. Glad to see you've regained your motivation. 😊

**Comment by asudbury** [comment]
@lothrop when is Mvx 4.0 due to go live?

**Comment by lothrop** [comment]
@asudbury I'm guessing February.

**Comment by lothrop** [comment]
Can this be closed?

**Comment by asudbury** [comment]
Not yet - there is still a bug I need to fix - I don't I've wired up the view to the xib correctly - a also have the same issue with storyboards!

**Comment by asudbury** [comment]
Released with version 4.0.0
