### ISSUE TITLE
VS2015 issues and enhancements

### ISSUE THREAD

**Issue by asudbury** [asudbury/NinjaCoderForMvvmCross#192]
We seem to have successfully (at long last) got ninja working for VS2015 :-)

https://github.com/asudbury/NinjaCoderForMvvmCross/issues/170

version 3.8.4 installer
 
https://www.dropbox.com/s/8fdax01xkhk5fty/NinjaCoderMvvmCross.vsix.vsix?dl=0

Here we should add issues and suggested enhancements - the main goal however is to get a VS2015 version out to all those people that want one - issues and enhancements will be rated accordingly to try and get a version out to public in January 2016

thanks for all the help - you wouldn't believe how difficult this has been to get this far!!

**Comment by SergioZgz** [comment]
I'm trying right now :) forget my tweet I will tell you any problem here :)

**Comment by asudbury** [comment]
the new version 3.9.0 (BETA) is ready for test if anyone is interested - it also supports MvvmCross 4.0.

i don't expect it to be perfect - but i have done a lot of testing and works for me :-)

Xib and StoryBoards dont seem to be working for MvvmCross solutions -  looking for help there and im not sure i have the Android project correct for MvvmCross looking for someone to take a look for me.

Apart from the 2 above issues it appears to be ok :-)

**Comment by lothrop** [comment]
Awesome! Is it under the same link?

**Comment by asudbury** [comment]
just uploaded it (it is the same line)

https://www.dropbox.com/s/8fdax01xkhk5fty/NinjaCoderMvvmCross.vsix.vsix?dl=0

**Comment by asudbury** [comment]
my new version:-

i have fixed a few issues with the build action for certain projects
sorted issues with Android projects
now supports Xib view for MvvmCross iOS projects.
have attempted to support StoryBoard for MvvmCross iOS projects - but im doing something wrong as it doesnt seem to work for me - need help :-)
a few UI enhancements

**Comment by asudbury** [comment]
really close to doing a public release - let me know if someone can help test (please)

**Comment by powerdude** [comment]
i can test

**Comment by SergioZgz** [comment]
I could test it too :)

**Comment by asudbury** [comment]
new installer below for beta version 3.9.1

https://goo.gl/zOHnn0

A couple of suggestions 

To speed things up go to Options/Build and select Use Local Config and Use Local Text Templates this will read the config files from your local PC rather than fetching them from github! 

Obviously using local files you wont get any updates i do to the templates on github until i republish a new version of the VS Addin.

Also can i suggest that you also go to Options/Projects and skip the screens you dont want to see during Add Projects wizards - some people will find all these options annoying im sure!

What im really looking for are 3 things before releasing:-

1. Is it as least as good in VS2015 as it was in VS2013 - im hoping its a lot better :-)
2. Does it work correctly with MvvmCross 4.0
3. Does xib files and storyboards work with MvvmCross and iOS projects

The last point i dont think is working but my connection to my Mac Book just wont work at the moment. I think there is an outlet missing not set correctly - i think its the outlet for the actual view.

If anyone  can figure out the error - we would need to amend the correspending Xib and StoryBoard files in the location below (Pull Requests would be welcome!!) - there are 3 xib files and 3 storyboard files.

https://github.com/asudbury/NinjaCoderForMvvmCross/tree/master/Config/TextTemplates/ItemTemplates/iOS

I intend to continue to look myself hopefully.

All feedback appreciated - thanks for your time.

**Comment by asudbury** [comment]
Have created a new thread for any issues we find

https://github.com/asudbury/NinjaCoderForMvvmCross/issues/206

**Comment by asudbury** [comment]
Released with version 4.0.0
