### ISSUE TITLE
MvvmCross namespace changes in Mvx v4.0

### ISSUE THREAD

**Issue by asudbury** [asudbury/NinjaCoderForMvvmCross#195]
hmm.....

not sure about that!

Its the sort of thing that you expect in the linux world :-)

that means Vs2013 Ninja will be broken when this goes public (or should i say the ability to use mvx 4.0)

to make ninja vs2015 work with these changes means i need change the project templates, item templates, text templates, nuget packages and ninja core code - plus all the testing!

with still some items to make ninja work with vs2015 still outstanding, a lack of interest from people at the moment and my busy work schedule next year its hard to see me continuing making ninja vs2015 a reality :-(

https://github.com/MvvmCross/MvvmCross/issues/1190

**Comment by WarBorg** [comment]
maybe make two versions of Ninja one for VS2013 and one for VS2015 like they did with productivity tools

**Comment by asudbury** [comment]
@WarBorg having a vs2013 and vs2015 versions wont solve the issues!

In fact we could support both vs2013 and vs2015 it just that i am choosing not to as its more time consuming!

99% of the code is shared between vs2013 and vs2015 and its the shared 'bit' that needs to change.

things do need to break sometimes to move things forward - the proposed changes around namespaces is good and something I wanted to see along time ago!

BUT and it is a big BUT in my opinion.

You change a public API at your peril and I'm not sure that's been thought through - consumers of APIs care little that 'things have been tidied up' all they care about is that THEIR program is broken - or worse the tool (the ninja) they use is now broken.

it feels like a small problem is being fixed but is (potentially) creating a bigger problem - i guess time will tell :-)
 
There is some great stuff (and great people) going on with MvvmCross but I do feel like version 4,0 is out of control and new features seem to have been added once the product is in beta - that's a dangerous cycle to get into

It's their toy and if I don't like they cant quite reality tell me to get lost!!!

**Comment by WarBorg** [comment]
yes I know, I have tried to keep up with them but have no seen any tutorials for some time now and I am afraid I got a little lost, practically I was basing myself on Ninja to make the setup for me because really with MVX4.0 I got a little lost on what files I need to change and what to remove and what to add,  like right now I am still struggling with their example for Xamarin Form to make it work ...

**Comment by asudbury** [comment]
@WarBorg 

jabbr is a good place to get help with Mvx - https://jabbr.net/#/rooms/mvvmcross 

though recently you don't tend to see so many people on there these days - maybe there support has moved else where.

**Comment by WarBorg** [comment]
ok, I'll give it a try, thank you and I hope you will manage to get some things working next year, until then, happy holidays !!!

**Comment by martijn00** [comment]
@asudbury support has moved to Slack. If you want to join go to: https://xamarinchat.herokuapp.com/

I would love to work together to get NinjaCoder working with the upcoming 4.0 release!

@WarBorg We are working on a new website with new tutorials and samples for the MvvmCross 4.0 release.

**Comment by asudbury** [comment]
hi @martijn00 

you need to stop add new features to the v4.0 release - you are making it a moving target!

beta (as im sure you know) should not change the public interface just the internals.

**Comment by martijn00** [comment]
Thanks for your feedback, i appreciate it. We discussed this with the MvvmCross team a while ago, and we agree on this. We are planning to just finish 4.0 now, and from there on use a new strategy with releases. I would be happy if you join the discussion with us!

**Comment by asudbury** [comment]
@martijn00 I'm happy to join in with the discussions :-)

**Comment by martijn00** [comment]
It might be good to step into the discussion at https://github.com/MvvmCross/MvvmCross/issues/1190 or even make a new issue for this. We can continue from there on.

**Comment by asudbury** [comment]
that whole discussion should NEVER had made its way into version 4.0!

I don't think I would be liked if I step in add that!

from a purely selfish (ninja) point of view you should back out the namespace changes - that's just unacceptable once you hit beta - should we start a discussion on that topic?

i'm here to help - honest!!

**Comment by martijn00** [comment]
One problem for us was that we didn't want to go into beta yet, but where forced by Nuget. After an alpha9 version you can only go to beta. This problem would appear again on beta9, and we would need to make a RC1.

**Comment by asudbury** [comment]
Your right! - i thought that had been implemented as part of nuget 3.x.x 

Looks like nuget folks back tracked on Semantic Versioning 2.0.0 support :-(

http://blog.nuget.org/20140924/supporting-semver-2.0.0.html

**Comment by asudbury** [comment]
@martijn00 when is Mvx 4.0 due to get out of beta and will be generally available?

I have started making changes in prep for Mvx 4.0 - but the next set of changes depend when it will be released (i have an option to try and support Mvx 3.5.1 AND Mvx 4.0 in some way - or to ditch 3.5.1 if v4 is soon)

**Comment by asudbury** [comment]
Released with version 4.0.0
