### ISSUE TITLE
dont include MvxBindingAttributes.xml in nuget package

### ISSUE THREAD

**Issue by asudbury** [asudbury/NinjaCoderForMvvmCross#200]
Im assuming i no longer need to include MvxBindingAttributes.xml in nuget package as it appears to be in MvvmCross.Binding.Droid

Can anyone confirm?  @lothrop @martijn00

**Comment by lothrop** [comment]
:+1:

**Comment by asudbury** [comment]
thanks @lothrop

**Comment by martijn00** [comment]
Yes that is correct.

**Comment by asudbury** [comment]
Released with version 4.0.0
