### ISSUE TITLE
Setting start-up project doesn't work

### ISSUE THREAD

**Issue by agilehobo** [asudbury/NinjaCoderForMvvmCross#209]
After creating the solution, the PCL project is the start-up one even I selected Android or iOS project.

It happens with version 4.0.0

**Comment by asudbury** [comment]
@agilehobo  I'm working on version 4.1.0 which will allow the changing of project names suffixes  (and the start of support for windows universal).

I cant recreate the startup project issue you describe if i do a private build with better logging and tracing can you retest for me and provide a trace file so i can investigate?

**Comment by asudbury** [comment]
@agilehobo  V4.1.0 now released can you try and see if problem still occurs?

**Comment by agilehobo** [comment]
It still doesn't work.

BTW, you fixed the other issue I reported https://github.com/asudbury/NinjaCoderForMvvmCross/issues/210. The issue is not about the emulator cannot start. It's about there is no emulator appears in the drop down list to select to run.

**Comment by asudbury** [comment]
@agilehobo if you try and create an android project with out using the ninja coder do you get the emulator in the dropdown? have you got the android sdk installed etc?

**Comment by agilehobo** [comment]
@asudbury Yes and Yes

**Comment by asudbury** [comment]
Create a repo on GitHub of our solution  and send me a link.

**Comment by asudbury** [comment]
@agilehobo I'm closing this I don't believe this is a ninja issue - no one else has reported it  - I guess its a local issue for you.
