### ISSUE TITLE
Creating New Forms Project Failed to Include MvvmCross.Core

### ISSUE THREAD

**Issue by adamhill** [asudbury/NinjaCoderForMvvmCross#215]
Had to add this to the Forms project to enable it to compile.

Running NC 4.1.0

**Comment by asudbury** [comment]
Which Framework did you select? I'm assuming 'MvvmCross and Xamarin Forms'

If you post your ninjareadme.txt file ill take a look.

**Comment by adamhill** [comment]
Yes. I tried the suggestion from Twitter but it failed to add the UWP project, even though it was selected in the Wizard.

Attached is the text of the error dialog that popped up, the last entries of the ActivityLog.XML and the NinjaReadMe that was created at the end. There is no UWP node for the main project, but there is a Test project for UWP in the Test directory.

I am running the latest release Win 10 SDK, VS 2015 Update 2. All my Anniversary 10 SDK work is isolated in a separate VM.

Thanks.

[ninjacoder_bug.txt](https://github.com/asudbury/NinjaCoderForMvvmCross/files/253636/ninjacoder_bug.txt)
[NinjaReadMe.txt](https://github.com/asudbury/NinjaCoderForMvvmCross/files/253638/NinjaReadMe.txt)

**Comment by asudbury** [comment]
@adamhill It is reporing it cant find/load the project template NinjaCoder.WindowsUniversal.zip.

Can you see if the file exists on your machine?

**Comment by adamhill** [comment]
I have checked in C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE in ItemTemplates and ProjectTemplate and did not see it, also looked in /My Documents\VIsual Studio 2015\Templates and didn't see it either.

Are these the correct folders for Ninja's templates?

**Comment by asudbury** [comment]
@adamhill no it doesnt store them in those directories.

I think i have spotted the problem - i dont think the windows universal template is being deployed.

i have 2 choices build 4.1.1 (with just the missing template includes) or build 4.2.0 - which will be the mvvmcross and xamarin forms windows universal support.

**Comment by adamhill** [comment]
I am not in a huge rush. I have become gainfully unemployed recently and am
catching up on MVVM framework advancements for Xamarin and UWP.

If you can give me quick instructions, I am more than happy to do it
manually.

 I am really liking MvvmCross, it has come along quite a bit since the
Cirrious and HotTuna days :-)

**Comment by asudbury** [comment]
I think I'll do a 4.1.1 - give me an hour.

MvvmCross is excellent very well put together.

Have a look at Xamarin Forms too.

Or even better mix the two using the ninja :-)

**Comment by asudbury** [comment]
@adamhill  Actually having a closer look it looks the template is deployed - can you scan your

c:\users\YOURLOGIN\AppData\Local\Microsoft\VisualStudio\14.0\Extensions

**Comment by meddyrainzo** [comment]
What did come out of this? I am also having the missing templates error when I try to create the UWP project


ERROR .WindowsUniversal not added. exception The system cannot find the file specified. (Exception from HRESULT: 0x80070002) (template NinjaCoder.WindowsUniversal.zip)

**Comment by meddyrainzo** [comment]
Funny enough, I can find the NinjaCoder.WindowsUniversal.Zip in my visual studio extensions folder

**Comment by asudbury** [comment]
Interesting! The installer can't be registering it as a project template!

Will take a look.

**Comment by meddyrainzo** [comment]
Okay thank you!

**Comment by asudbury** [comment]
@adamhill @meddyrainzo 

I have uploaded an internal build (this will be version 4.2 to support Windows Universal and 'MvmmCross and Xamarin Forms' solutions.

Can you install and see if you problems go away.

https://www.dropbox.com/s/au0pa0s2tksfs6i/NinjaCoderMvvmCross.vsix?dl=0

**Comment by meddyrainzo** [comment]
Sure thing - Give me an hour and I'll get back to you

**Comment by meddyrainzo** [comment]
After trying it, it does add the file but gives the following log errors

14 May 16 16:11:24 688 ** ERROR ** Cannot add a link to the file App.xaml.cs. There is already a file of the same name in this folder.
14 May 16 16:11:24 807 ** ERROR **    at EnvDTE.ProjectItems.AddFromFile(String FileName)
   at Scorchio.VisualStudio.Extensions.ProjectExtensions.AddToFolderFromFile(Project instance, String folderName, String fileName)
   at Scorchio.VisualStudio.Extensions.ProjectExtensions.AddTextTemplate(Project instance, String projectFolder, String fileName, String textOutput, Boolean outputTextTemplateContentToTraceFile)
   at Scorchio.VisualStudio.Services.ProjectService.AddTextTemplate(TextTemplateInfo textTemplateInfo, Boolean outputTextTemplateContentToTraceFile)
   at NinjaCoder.MvvmCross.Services.TextTemplatingService.AddTextTemplates(String statusBarMessage, IEnumerable`1 textTemplates)
   at NinjaCoder.MvvmCross.Services.ProjectsService.AddProject(String path, ProjectTemplateInfo projectInfo)
   at NinjaCoder.MvvmCross.Services.ProjectsService.AddProjects(IVisualStudioService visualStudioServiceInstance, String path, IEnumerable`1 projectsInfos)
   at NinjaCoder.MvvmCross.Controllers.ProjectsController.Process(ProjectsViewModel projectsViewModel, ApplicationOptionsViewModel applicationOptionsViewModel, NinjaCoderOptionsViewModel ninjaCoderOptionsViewModel, ApplicationSamplesOptionsViewModel applicationSamplesOptionsViewModel, ViewsViewModel viewsViewModel, PluginsViewModel pluginsViewModel, NugetPackagesViewModel nugetPackagesViewModel, XamarinFormsLabsViewModel xamarinFormsLabsViewModel)
   at NinjaCoder.MvvmCross.Controllers.ProjectsController.Run()

**Comment by asudbury** [comment]
@meddyrainzo a new installer to not try and add file to project if it already exists (the error you reported above)

https://www.dropbox.com/s/73b99ysl2m49rqi/NinjaCoderMvvmCross.vsix?dl=0

**Comment by asudbury** [comment]
@meddyrainzo is the issue fixed with the above build - i will be pushing it out in the couple of days.

**Comment by meddyrainzo** [comment]
@asudbury sorry for the late response I was caught up with a lot of work. I have I'll try it out today by 6pm and get back to you.

**Comment by adamhill** [comment]
I will also try today to test.

**Comment by meddyrainzo** [comment]
@asudbury Everytime I try to add the projects, visual studio restarts. Waiting to hear what @adamhill gets when he tries it out

**Comment by asudbury** [comment]
That's not good!!

If you can post the trace log I'll take a look.

**Comment by meddyrainzo** [comment]
Okay give me an hour

**Comment by meddyrainzo** [comment]
@asudbury not to sound like a noob, but how exactly do I check the trace log. Once I finish with the selection with the ninjacoder, it immediately shows the "Visual studio has stopped working dialog". Then goes to "Visual studio is restarting" and then everything restarts

**Comment by asudbury** [comment]
What you need to do is the following:-

Tools\Ninja Coder for MvvmCross and Xamarin Forms\Clear Trace Log

Do the adding of projects (i assume visual studio restarts)

Tools\Ninja Coder for MvvmCross and Xamarin Forms\View Trace Log

then either add the file as an attachment here or paste in the contents of the file.

Note:- I am looking into making it easier to post trace logs!

**Comment by asudbury** [comment]
@meddyrainzo also try NOT adding the Windows Universal project and see if that works.

**Comment by meddyrainzo** [comment]
Okay. On it

**Comment by meddyrainzo** [comment]
Okay, I don't know if this is how it is supposed to work but if you have an empty solution, upon selecting the projects and clicking next, you get a popup saying "The directory is empty please select another one". Furthermore, even with UWP unselected, visual studio still restarts. Finally, when I try to check the log file it says "the process cannot access the file because it is being used by another process". When I click ok, I get a blank notepad page. 

That's the summary of everything at the moment. @asudbury

**Comment by asudbury** [comment]
If you download debugview (i have provided a link below) hopefully we can see what is happening 

https://www.dropbox.com/s/51v6y6whqgfr97h/Dbgview.exe?dl=0

**Comment by meddyrainzo** [comment]
Here is the log file generated. It was pretty long. Hopefully I did it right. Write to confirm if I did it right
[NinjaDebug.txt](https://github.com/asudbury/NinjaCoderForMvvmCross/files/273284/NinjaDebug.txt)

**Comment by asudbury** [comment]
@meddyrainzo  thats the log from debugtrace - unfortunately it doest contain and trace messages from ninja coder!

leave it with me i need to think about this a bit more - thanks for your help.

**Comment by meddyrainzo** [comment]
Okay. Sorry I couldn't be of as much help

**Comment by asudbury** [comment]
@adamhill   can you try the new internal build please?

https://www.dropbox.com/s/au0pa0s2tksfs6i/NinjaCoderMvvmCross.vsix?dl=0

**Comment by meddyrainzo** [comment]
@adamhill I would like to try it as well. The link is broken for me

**Comment by asudbury** [comment]
try this one.

https://www.dropbox.com/s/73b99ysl2m49rqi/NinjaCoderMvvmCross.vsix?dl=0

**Comment by meddyrainzo** [comment]
@asudbury I got the same results as before. Please can you check the link you sent to ensure it is the latest version because when I installed it, I got an alert that I already have that version installed or something of that nature

**Comment by asudbury** [comment]
@meddyrainzo 

do you want to try this version?

there is a new option - Options/Tracing/Write Trace and Error Log to NinjaReadMe.txt - if it fails check this option and then post the readme file.

https://www.dropbox.com/s/37mvsqg4rs73c7k/NinjaCoderMvvmCross.vsix?dl=0

**Comment by meddyrainzo** [comment]
@asudbury, sure thing. Give me 30 minutes

**Comment by meddyrainzo** [comment]
@asudbury It works for me now. Downloaded all the files. (Side note)I had to do a clean on the Universal Windows project first to get rid of the squiggly lines in the Setup.cs but it works now. Great work!

**Comment by meddyrainzo** [comment]
@asudbury
UPDATE :  When using it in a solution with projects, the setup classes(for UWP) and the view classes that come with the installation seem to be off. So does the mainViewModel. It tries to access these files from a folder above the current folder and gives the "The file has either been moved or deleted" error. Using it with empty solutions however, seem to give the desired result

**Comment by asudbury** [comment]
@meddyrainzo i think this issue is now fixed (but we/you need to open a new issue as described above)

closing this issue means i can than release 4.2 (and start work on the issue above)

does that sound ok?

**Comment by meddyrainzo** [comment]
@asudbury sure thing on my end. I'll do that later today

**Comment by asudbury** [comment]
fixed in version 4.2.0
