### ISSUE TITLE
Mvvmcross Plugins - Update to 4.x.x 

### ISSUE THREAD

**Issue by benhysell** [asudbury/NinjaCoderForMvvmCross#218]
Adding a plugin for Mvvmcross, say the messenger plugin, pulls down the 3.5.x version of the plugin, and not the newer 4.x.x versions.

**Comment by asudbury** [comment]
@benhysell Ive quickly updated the plugins config file - do you want to give it another try (you will probably need to restart visual studio as it will cache the config file entries)

**Comment by benhysell** [comment]
Can do, where do I drop it?  I'm running your last release.

**Comment by asudbury** [comment]
its hosted on GitHub - yo don't need to install anything :-)

**Comment by benhysell** [comment]
Nice!

And done...worked like a charm.  Thanks!

**Comment by asudbury** [comment]
glad to hear it :-)
