### ISSUE TITLE
NC always uses Moq as mocking framework

### ISSUE THREAD

**Issue by pauldekart** [asudbury/NinjaCoderForMvvmCross#221]
Hi,

NinjaCoder seems to have a problem with NSubstitute. Selecting it as mocking framework does not apply by creating new project. NC always use Moq instead.

Btw. great plugin!

**Comment by florkl** [comment]
Hi @pauldekart,
I could imagine that your issue has the same reason as #219 . Please have a look at my workaround.

**Comment by asudbury** [comment]
Fixed in Version 4.2.1 which is now available on the Visual Studio Market Place.

https://marketplace.visualstudio.com/items?itemName=NinjaCoderforMvvmCross.NinjaCoderForMvvmCrossandXamarinForms
