### ISSUE TITLE
Platform Test Projects not created

### ISSUE THREAD

**Issue by ananth-racherla** [asudbury/NinjaCoderForMvvmCross#222]
Found in Visual Studio 2015 enterprise edition. I am currently running version 4.2.0 of Ninja Coder.

I did select "Create Platform tests" on the opening screen. Attached are some screenshots for reference. You will notice in the final screen that the platform test projects are missing.  

Seemed to work fine on a box running Visual Studio Community Edition 2015 however.

![platformtestsspecified](https://cloud.githubusercontent.com/assets/14127511/16507352/1d7e811a-3ede-11e6-9874-e7551a8d586c.PNG)

![finishedaddingprojects](https://cloud.githubusercontent.com/assets/14127511/16507351/1d7d5b6e-3ede-11e6-9612-f26c115a70df.PNG)

.

**Comment by florkl** [comment]
Hi @ananth-racherla,
please have a look at issue #219 and my workaround. I could imagine that your problem has the same reason.

**Comment by Telavian** [comment]
The workaround worked for me also.
Thanks.

**Comment by asudbury** [comment]
@ananth-racherla see issue below - hopefully will solve you issue with v4.2.1

@Telavian may solve issues you were having too

https://github.com/asudbury/NinjaCoderForMvvmCross/issues/225

**Comment by asudbury** [comment]
Fixed in Version 4.2.1 which is now available on the Visual Studio Market Place.

https://marketplace.visualstudio.com/items?itemName=NinjaCoderforMvvmCross.NinjaCoderForMvvmCrossandXamarinForms
