### ISSUE TITLE
Options not saved

### ISSUE THREAD

**Issue by adaxer** [asudbury/NinjaCoderForMvvmCross#224]
Hello,

I wanted to set the project suffix for the WindowsUniversal projects to UWP. So I did, but whenever I create projects or open the options again, the standard value WindowsUniversal  is shown.

I wanted to tweak this, but I cannot find the location where NinjaCoderForMvvmCross keeps this settings.

I'd appreciate very much if this is fixed, or if you can tell me the location. Thanks very much (also for this great tool!!)

Andreas

**Comment by asudbury** [comment]
@adaxer see issue below - hopefully will solve you issue with v4.2.1

https://github.com/asudbury/NinjaCoderForMvvmCross/issues/225

**Comment by adaxer** [comment]
Hi Adrian,

indeed, the issue has gone with 4.2.1. Also the reg entry is there now. Thanks very much!
(Keep it up, by the way – the ninja coder is awesome ☺)

Best regards
Andreas

Von: Adrian Sudbury [mailto:notifications@github.com]
Gesendet: Freitag, 30. Dezember 2016 15:30
An: asudbury/NinjaCoderForMvvmCross <NinjaCoderForMvvmCross@noreply.github.com>
Cc: Andreas Daxer <info@andreas-daxer.de>; Mention <mention@noreply.github.com>
Betreff: Re: [asudbury/NinjaCoderForMvvmCross] Options not saved (#224)


@adaxer<https://github.com/adaxer> see issue below - hopefully will solve you issue with v4.2.1

#225<https://github.com/asudbury/NinjaCoderForMvvmCross/issues/225>

**Comment by asudbury** [comment]
Fixed in Version 4.2.1 which is now available on the Visual Studio Market Place.

https://marketplace.visualstudio.com/items?itemName=NinjaCoderforMvvmCross.NinjaCoderForMvvmCrossandXamarinForms
