### ISSUE TITLE
Refractored.Xam.Settings  can not find

### ISSUE THREAD

**Issue by gitlsl** [asudbury/NinjaCoderForMvvmCross#226]
I crate a wpf project 
in the ```SettingsServicecs.cs```  it can not find  ```using Refractored.Xam.Settings;```
so I change to ```using Plugin.Settings;  using Plugin.Settings.Abstractions;```  by resharper and is ok

**Comment by asudbury** [comment]
@gitlsl good spot :-)

I'm guessing the namespaces must have changed at some point - i will update the nuget package to fix (doesnt require any ninja coder changes)

**Comment by asudbury** [comment]
nuget package updated - should work ok now.
