### ISSUE TITLE
Windows Universal missing file Presenter.cs.t4

### ISSUE THREAD

**Issue by pedropete11** [asudbury/NinjaCoderForMvvmCross#228]
When creating project for mvvmcross and xam forms, with Win Universal project.
Generates error (404) Not Found when WebClient.OpenRead requests file 
http://raw.githubusercontent.com/asudbury/NinjaCoderForMvvmCross/master/Config/TextTemplates\ProjectTemplateItems\WindowsUniversal\MvvmCrossAndXamarinForms\Presenter.cs.t4

But in source, file is in sub-folder Presenters.

Workaround: In NC Options, Build, check 'Use Local Text Template Files'

**Comment by asudbury** [comment]
thinking about it - as we now have 2 bugs ill create a new release ans
installer - are you ok to test for me?

**Comment by pedropete11** [comment]
Yes, I'd be happy to test.

There's a work-around for the missing file issue:

Workaround: In NC Options, Build, check 'Use Local Text Template Files'

Not sure if I have all the latest, of course, but the project creation
worked.

**Comment by asudbury** [comment]
@pedropete11 i have moved the file on github  doesnt need a new build as its a file hosted on github (will have roll in to the next release for the pc cached files to be updated but very few people use those!)

can you take a look please?

**Comment by pedropete11** [comment]
Yes, it works now.
