### ISSUE TITLE
Windows Universal setup.cs assignment to self warning

### ISSUE THREAD

**Issue by pedropete11** [asudbury/NinjaCoderForMvvmCross#230]
In WU - setup.cs, ctor: the line
launchActivatedEventArgs = launchActivatedEventArgs;

will generate an 'assign to self' warning and the class readonly launchActivatedEventArgs field will remain null. Then, the Init(launchActivatedEventArgs) call will generate a null exception.
A rename will fix the issue.

**Comment by asudbury** [comment]
@pedropete11 can I take the readonly off the property declaration - will that fix it?

**Comment by asudbury** [comment]
@pedropete11 i have change the name of the param as you suggested - doesnt need a new build as its a file hosted on github (will have roll in to the next release for the pc cached files to be updated but very few people use those!)

can you take a look please?

**Comment by pedropete11** [comment]
Great.
I also realized that I had unchecked the option to use "this" syntax. By
leaving "this." syntax in there, it would also work.
With renaming, it will work correctly, regardless of the option setting.
Thanks!
